PRAGMA foreign_keys = ON;

CREATE TABLE USERS(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USERNAME TEXT NOT NULL,
	PASSWORD TEXT NOT NULL,
	FULLNAME TEXT
    );

CREATE TABLE CARMODELS(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	BRAND TEXT NOT NULL,
	MODEL TEXT NOT NULL,
	MODEL_TYPE TEXT NOT NULL, 
	EXTRA TEXT
    );   

CREATE TABLE CARS(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CARMODEL_ID INTEGER NOT NULL,
	OWNER_NAME TEXT NOT NULL,
	LICENSE_PLATE_NUMBER TEXT,
	VIN TEXT NOT NULL,
	PRODUCTION_DATE TEXT NOT NULL,
	START_TRAFFIC_DATE TEXT,
	FOREIGN KEY(CARMODEL_ID) REFERENCES CARMODELS(ID) 
    );